# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=2.0.25.14
last_mod_version=2.0.25.13

# Common
minecraft_version=1.20.1
minecraft_short_version=1.20
whitenoise_version=1.1.1
whitenoise_range=[1.0.0, 2.0.0)
mixin_version=0.8.5
# https://minecraft.wiki/w/Pack_format
pack_format=15
java_version=17

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2023.09.03

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=47.4.8
forge_version_range=[46,)
forge_mc_version_range=[1.20,1.20.2)

# Integration and Testing Mods
# https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version=15.20.0.116
mantle_version=1.11.79
tic_version=3.10.2.92
tic_version_range=[3.9.1.24,)
se_version=1.20.1-6.2.4.2
ts_version=1.20.1-5.0.0.5
probe_version=6106996
curios_version=5.14.1
patchouli_version=1.20.1-84.1
ie_version=6206989
botania_version=6870713
create_version=6641603
create_min_version=0.5.1
registrate_version=MC1.20-1.3.11
arsnouveau_version=6688854
geckolib_version=6789487
aquaculture_version=6296111
alexsmobs_version=5698791
citadel_version=6702068
malum_version=6646111
malum_minimum_version=1.6
lodestone_version=6213794
undergarden_version=5182632
projecte_version=4901949
terrablender_version=6290448
architectury_version=5137938
mekanism_version=6552911
mekanism_tools_version=6552915
mythicbotany_version=6702112
iceandfire_version=5633453
libx_version=1.20.1-5+
beyond_earth_version=5622318
cyanide_version=5778405
consecration_version=5005745
ad_astra_version=6262032
resourceful_lib_version=5659871
botarium_version=5486070
resourceful_config_version=6231176
apotheosis_version=6461960
attributeslib_version=5634071
placebo_version=6274231
twighlight_forest_version=5468648
ars_elemental_version=6390889
deeperdarker_version=5906086

# Mod options
mod_display_name=Tinkers' Construct Integration and Tweaks
mod_id=tcintegrations
mod_name=TCIntegrations
mod_author=wendall911
mod_credits=ashar42
license=MIT
mod_description=Tinkers' Construct Mod Integraions and Tweaks.
mod_update_branch=1.20.1

# CurseForge/Modrinth Options
# Global properties are located in ~/.gradle/gradle.properties
# DO NOT put private keys here
curseforge_api_key_prop=ticurseApiKey
curseforge_id=602680
curseforge_slug=tcintegrations
modrinth_api_key_prop=modrinthKey
modrinth_id=jNa5P8yc
discord_webhook_prop=tiDiscordWebhook
discord_dryrun_webhook_prop=discordDryrunWebhook
release_type=release
release_versions=1.20.1
