# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=2.0.25.3
last_mod_version=2.0.25.2

# Common
minecraft_version=1.19.2
minecraft_short_version=1.19
java_version=17

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2022.11.27

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=43.5.1
forge_version_range=[43,)
forge_mc_version_range=[1.19.2,1.19.3)

# Integration Mods
jei_version=11.8.1.1034
mantle_version=1.10.48
tic_version=3.8.5.58
tic_version_range=[3.8,)
se_version=6984493
tinkersurvival_version=6984710
probe_version=6.2.0-6
curios_version=5302436
patchouli_version=1.19.2-77
ie_version=5222176
botania_version=4557912
create_version=4835190
create_min_version=0.5.1
registrate_version=MC1.19-1.1.5
arsnouveau_version=5171729
geckolib_version=4407241
aquaculture_version=4074684
alexsmobs_version=4159154
citadel_version=4556677
malum_version=4952075
malum_minimum_version=1.5
lodestone_version=4636991
undergarden_version=4057184
projecte_version=4860858
terrablender_version=4618490
byg_version=5116293
corgi_version=4554111
mekanism_version=4644795
mekanism_tools_version=4644799
mythicbotany_version=4546050
iceandfire_version=5037952
libx_version=1.19.2-4.2+
beyond_earth_version=5115692
cyanide_version=3832812
consecration_version=4814166
ad_astra_version=4643668
resourceful_lib_version=4477753
botarium_version=5118248
resourceful_config_version=4444198
apotheosis_version=5753172
placebo_version=6274259
twighlight_forest_version=4389567
ars_elemental_version=5255886
deeperdarker_version=4812297

# Mod options
mod_name=TCIntegrations
mod_id=tcintegrations
mod_author=wendall911
mod_credits=ashar42
license=MIT
issue_tracker=https://github.com/wendall911/TCIntegrations/issues
mod_description=Tinkers' Construct Mod Integraions and Tweaks.
mod_update_branch=1.19.2

# CurseForge/Modrinth Options
release_type=release
release_versions=1.19.2
